spring:
  application:
    name: aaaa
  datasource:
    url: jdbc:mysql://192.168.5.61/aaaa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: quinit
    region: cn-beijing